import { Lead, Call, TeamMember } from './types'

export const mockLeads: Lead[] = [
  {
    id: '1',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    phone: '+91 98765 43210',
    property: 'Downtown Apartment - 2BHK',
    status: 'qualified',
    source: 'website',
    value: 45000000,
    notes: 'Very interested in urban properties. Pre-approved for home loan.',
    createdAt: new Date('2024-05-15'),
    lastContactedAt: new Date('2024-06-08'),
    assignedTo: 'agent-1',
  },
  {
    id: '2',
    firstName: 'Priya',
    lastName: 'Sharma',
    phone: '+91 98765 43211',
    property: 'Suburban Family Home - 3BHK',
    status: 'contacted',
    source: 'referral',
    value: 65000000,
    notes: 'Family of 4. Looking for good schools. Second viewing scheduled.',
    createdAt: new Date('2024-06-01'),
    lastContactedAt: new Date('2024-06-05'),
    assignedTo: 'agent-2',
  },
  {
    id: '3',
    firstName: 'Amit',
    lastName: 'Patel',
    phone: '+91 98765 43212',
    property: 'Luxury Beach House - 3BHK',
    status: 'proposal',
    source: 'social-media',
    value: 85000000,
    notes: 'Interested in vacation rental potential. Sent over analysis.',
    createdAt: new Date('2024-04-10'),
    lastContactedAt: new Date('2024-06-07'),
    assignedTo: 'agent-1',
  },
  {
    id: '4',
    firstName: 'Vikram',
    lastName: 'Singh',
    phone: '+91 98765 43213',
    property: 'Commercial Property Portfolio',
    status: 'closed',
    source: 'cold-call',
    value: 250000000,
    notes: 'Corporate investor. Multiple properties acquired. Excellent client.',
    createdAt: new Date('2024-03-20'),
    lastContactedAt: new Date('2024-06-01'),
    assignedTo: 'agent-2',
  },
  {
    id: '5',
    firstName: 'Anjali',
    lastName: 'Verma',
    phone: '+91 98765 43214',
    property: 'Hill Station Property - 2BHK',
    status: 'new',
    source: 'website',
    value: 32000000,
    notes: 'Inquiry received today. Follow up tomorrow.',
    createdAt: new Date('2024-06-08'),
    assignedTo: 'agent-1',
  },
  {
    id: '6',
    firstName: 'Suresh',
    lastName: 'Gupta',
    phone: '+91 98765 43215',
    property: 'Modern Townhouse - 3BHK',
    status: 'qualified',
    source: 'referral',
    value: 58000000,
    notes: 'First-time buyer. Very organized. Great communication.',
    createdAt: new Date('2024-05-22'),
    lastContactedAt: new Date('2024-06-06'),
    assignedTo: 'agent-2',
  },
  {
    id: '7',
    firstName: 'Neha',
    lastName: 'Desai',
    phone: '+91 98765 43216',
    property: 'Premium High-rise Penthouse - 4BHK',
    status: 'contacted',
    source: 'cold-call',
    value: 180000000,
    notes: 'High-end buyer. Looking for move-in ready. Flexible timeline.',
    createdAt: new Date('2024-05-30'),
    lastContactedAt: new Date('2024-06-07'),
    assignedTo: 'agent-1',
  },
  {
    id: '8',
    firstName: 'Arjun',
    lastName: 'Reddy',
    phone: '+91 98765 43217',
    property: 'Heritage Property - 5BHK',
    status: 'new',
    source: 'website',
    value: 92000000,
    notes: 'Restoration enthusiast. Interested in renovation projects.',
    createdAt: new Date('2024-06-08'),
    assignedTo: 'agent-2',
  },
]

export const mockCalls: Call[] = [
  {
    id: 'call-1',
    leadId: '1',
    duration: 28,
    date: new Date('2024-06-08'),
    notes: 'Discussed financing options and timeline for purchase.',
    summary: 'Buyer enthusiastic about the downtown loft. Requested information about closing costs and timeline.',
    outcome: 'positive',
  },
  {
    id: 'call-2',
    leadId: '2',
    duration: 35,
    date: new Date('2024-06-05'),
    notes: 'Family viewed property. Questions about property taxes and school district.',
    summary: 'Positive viewing. Family has two school-age children. Concerned about property tax rates in the district.',
    outcome: 'positive',
  },
  {
    id: 'call-3',
    leadId: '3',
    duration: 22,
    date: new Date('2024-06-07'),
    notes: 'Sent property analysis. Discussed vacation rental potential.',
    summary: 'Interested in vacation rental analysis. Reviewing financial projections. Will call back by end of week.',
    outcome: 'positive',
  },
  {
    id: 'call-4',
    leadId: '1',
    duration: 15,
    date: new Date('2024-06-01'),
    notes: 'Initial consultation. Buyer pre-qualified.',
    summary: 'Strong financial position. Pre-approved mortgage. Ready to move forward.',
    outcome: 'positive',
  },
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'agent-1',
    name: 'Alice Johnson',
    email: 'alice.johnson@realty.com',
    role: 'agent',
    leadsAssigned: 4,
  },
  {
    id: 'agent-2',
    name: 'Bob Smith',
    email: 'bob.smith@realty.com',
    role: 'agent',
    leadsAssigned: 4,
  },
  {
    id: 'manager-1',
    name: 'Carol Davis',
    email: 'carol.davis@realty.com',
    role: 'manager',
    leadsAssigned: 0,
  },
]

export const mockTeamStats = {
  totalLeads: mockLeads.length,
  closedDeals: mockLeads.filter((l) => l.status === 'closed').length,
  totalValue: mockLeads.reduce((sum, l) => sum + l.value, 0),
  avgLeadValue: mockLeads.reduce((sum, l) => sum + l.value, 0) / mockLeads.length,
}
